twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Kafka
    - Elasticsearch
  welcome-message: "Welcome to the Twitter to Kafka Service! Listening for tweets..."
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 100000
  multiplier: 2.0
  max-attempts: 3
  sleep-time-ms: 2000